server:
  port: 8080
  servlet:
    session:
      cookie:
        name: DEMOSESSION

spring:
  application:
    name: demo-service

  security:
    oauth2:
      client:
        registration:
          # IDSA Registry (centralized auth)
          idsa:
            client-id: demo-service
            client-secret: demo-secret
            scope: openid,profile,connector.read
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          # DID Registry (decentralized auth)
          did:
            client-id: demo-service
            client-secret: demo-secret
            scope: openid,profile,connector.read
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

        provider:
          # Classic IDSA Registry
          idsa:
            issuer-uri: http://localhost:9000
          # DID-based registry
          did:
            issuer-uri: http://localhost:9100

logging:
  level:
    org.springframework.security: INFO